python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SS3L1b.py --output slides/slides_20201109_object_mig/ --outputfile "SS3L1b_v1.tex" --inputFolder "/Users/ploww/dropbox_meng/HEP/Results/BSM4tops/Slides20201106_new_offline_production/results/" --compile
python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SR.py --output slides/slides_20201109_object_mig/ --outputfile "SR_v1.tex" --inputFolder "/Users/ploww/dropbox_meng/HEP/Results/BSM4tops/Slides20201106_new_offline_production/results/" --compile
python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SR_6j.py --output slides/slides_20201109_object_mig/ --outputfile "SR_6j_v1.tex" --inputFolder "/Users/ploww/dropbox_meng/HEP/Results/BSM4tops/Slides20201106_new_offline_production/results/" --compile
python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SR_6j_2b.py --output slides/slides_20201109_object_mig/ --outputfile "SR_6j_2b_v1.tex" --inputFolder "/Users/ploww/dropbox_meng/HEP/Results/BSM4tops/Slides20201106_new_offline_production/results/" --compile


python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SS3L1b.py --output slides/slides_20201109_object_mig/ --outputfile "SS3L1b_v1.tex" --inputFolder "/atlas/data19/metsai/hbsm4top/bsm4topssml_fitter/bsm4top_plottool/object_migration/results/" --compile
python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SR.py --output slides/slides_20201109_object_mig/ --outputfile "SR_v1.tex" --inputFolder "/atlas/data19/metsai/hbsm4top/bsm4topssml_fitter/bsm4top_plottool/object_migration/results/" --compile
python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SR_6j.py --output slides/slides_20201109_object_mig/ --outputfile "SR_6j_v1.tex" --inputFolder "/atlas/data19/metsai/hbsm4top/bsm4topssml_fitter/bsm4top_plottool/object_migration/results/" --compile
python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SR_6j_2b.py --output slides/slides_20201109_object_mig/ --outputfile "SR_6j_2b_v1.tex" --inputFolder "/atlas/data19/metsai/hbsm4top/bsm4topssml_fitter/bsm4top_plottool/object_migration/results/" --compile



python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SS3L1b.py --output /lustre/umt3/user/metsai/slides/20201109_object_migration/ --outputfile "SS3L1b.tex" --inputFolder "/atlas/data19/metsai/hbsm4top/bsm4topssml_fitter/bsm4top_plottool/object_migration/results/" --compile
python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SR.py --output /lustre/umt3/user/metsai/slides/20201109_object_migration/ --outputfile "SR.tex" --inputFolder "/atlas/data19/metsai/hbsm4top/bsm4topssml_fitter/bsm4top_plottool/object_migration/results/" --compile
python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SR_6j.py --output /lustre/umt3/user/metsai/slides/20201109_object_migration/ --outputfile "SR_6j.tex" --inputFolder "/atlas/data19/metsai/hbsm4top/bsm4topssml_fitter/bsm4top_plottool/object_migration/results/" --compile
python generateSlides.py  --input slides/slides_20201109_object_mig/generation-SR_6j_2b.py --output /lustre/umt3/user/metsai/slides/20201109_object_migration/ --outputfile "SR_6j_2b.tex" --inputFolder "/atlas/data19/metsai/hbsm4top/bsm4topssml_fitter/bsm4top_plottool/object_migration/results/" --compile
